- name: Install Connect iT thumb
  ansible.builtin.command:
    cmd: connectit install thumb --url "https://{{ connectit_domain }}" --name "{{ ansible_host }}"
  environment:
    PASSWORD: "{{ connectit_admin_password }}"
