- name: Install Connect iT video
  ansible.builtin.command:
    cmd: "connectit install video --url 'https://{{ connectit_domain }}' --name '{{ ansible_host }}' {% if connectit_version is version('R3.20', '>=') %}--force{% endif %}"
  environment:
    PASSWORD: "{{ connectit_admin_password }}"
