- name: Download Connect iT binary
  ansible.builtin.get_url:
    url: "https://docs.cnctit.io/releases/connectit-{{ connectit_version }}"
    dest: /usr/sbin/connectit
    mode: 'u=rwx,g=rx,o=rx'
  when: connectit_binary is undefined

- name: Upload connectit binary
  ansible.builtin.copy:
    src: "{{ connectit_binary }}"
    dest: /usr/sbin/connectit
    mode: 'u=rwx,g=rx,o=rx'
  when: connectit_binary is defined
