- name: Install Edge Connect
  ansible.builtin.command:
    cmd: connectit install edge-connect --url "https://{{ connectit_domain }}" --name "{{ edgeconnect_name }}"
  environment:
    PASSWORD: "{{ connectit_admin_password }}"
